<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.11" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CCMC.Cloud.Api\CCMC.Cloud.Api.csproj" />
    <ProjectReference Include="..\..\src\CCMC.Cloud.Application\CCMC.Cloud.Application.csproj" />
    <ProjectReference Include="..\..\src\CCMC.Cloud.Infrastructure\CCMC.Cloud.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\CCMC.Cloud.Domain\CCMC.Cloud.Domain.csproj" />
    <ProjectReference Include="..\..\src\CCMC.Contracts\CCMC.Contracts.csproj" />
  </ItemGroup>

</Project>
