packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@nestjs/core': true
  '@serialport/bindings-cpp': true
  bcrypt: true
  esbuild: true

onlyBuiltDependencies:
  - "@nestjs/core"
  - bcrypt
  - esbuild
